### ISSUE TITLE
Character protection on State name

### ISSUE THREAD

**Issue by dsuurlant** [JetBrains/youtrack-workflows#2] opened 2014-02-11 14:32 UTC
YouTrack 5.0.6. throws the follow error when attempting to add the State field 'W/O verification': "Name shouldn't contain characters "<", "/", ">": name"

Appears to be protection from inserting HTML tags into the name.

-edit- This applies to the QA Verification workflow, https://github.com/JetBrains/youtrack-workflows/tree/5c65e76f2476f29a383ec56fb8f71108ae834f8a/QA%20Verification%20Process

**Comment by mariyadavydova** [comment] 2018-12-24 14:38
The issue is fixed in the JS version of this workflow (https://github.com/JetBrains/youtrack-workflows/tree/master/js/advanced-state-machine).

**Closed by mariyadavydova** 2018-12-24 14:38 UTC
Labels: bug
